# Navigation Links
#   To link a homepage block, specify the URL as a hash `#` followed by the
#     block's `id:` in `content/_index.md`.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Papers
    url: publications/
    weight: 30
  - name: Software
    url: software/
    weight: 40
  - name: Teaching
    url: /under-construction/
    weight: 50
  - name: Experience
    url: experience/
    weight: 60
  - name: News
    url: /under-construction/
    weight: 70
  - name: Contacts
    url: /under-construction/
    weight: 80